// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCe28ero4tHGPm8p_rivr968xE-3wAZFc',
    appId: '1:720534654360:web:a6891f5488b3aa2e9bafed',
    messagingSenderId: '720534654360',
    projectId: 'student-firestore',
    authDomain: 'student-firestore.firebaseapp.com',
    storageBucket: 'student-firestore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdgXy0yHUDax9jZlOoHwxhNz4uAbrLRy8',
    appId: '1:720534654360:android:773140eacc787fea9bafed',
    messagingSenderId: '720534654360',
    projectId: 'student-firestore',
    storageBucket: 'student-firestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0AvFpo1xj6XU-mzv41Xd41v_C6TLzVc',
    appId: '1:720534654360:ios:3e39d252dc2412a59bafed',
    messagingSenderId: '720534654360',
    projectId: 'student-firestore',
    storageBucket: 'student-firestore.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudentCrudFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT0AvFpo1xj6XU-mzv41Xd41v_C6TLzVc',
    appId: '1:720534654360:ios:3e39d252dc2412a59bafed',
    messagingSenderId: '720534654360',
    projectId: 'student-firestore',
    storageBucket: 'student-firestore.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudentCrudFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCe28ero4tHGPm8p_rivr968xE-3wAZFc',
    appId: '1:720534654360:web:e33c093baee5d9cc9bafed',
    messagingSenderId: '720534654360',
    projectId: 'student-firestore',
    authDomain: 'student-firestore.firebaseapp.com',
    storageBucket: 'student-firestore.firebasestorage.app',
  );
}
